#!/usr/bin/env python3
"""Generate an AI hero image and/or summary for a page's frontmatter.

Reads the page and has Claude produce a hero-image subject plus a short
page summary in one call. The image is generated by a local ComfyUI
instance using the fixed style clause from config.yaml and saved to an
img/ folder next to the page; `image:` / `image_style:` / `summary:`
are written into the frontmatter. The hooks/hero.py build hook renders
Title -> Summary -> Hero image -> content. A missing summary is filled
in automatically whenever an image is generated.

Usage:
    python new-hero.py docs/deep-time/memory-of-mankind/index.md
    python new-hero.py --all              # every content page without an image
    python new-hero.py --summary --all    # add summaries only (no ComfyUI)
    python new-hero.py <path> --force     # regenerate
    python new-hero.py <path> --style watercolor

Pages that already have a "## Summary" section (video pages) never get
a frontmatter summary. Settings live in config.yaml. Requires the
claude CLI on PATH; ComfyUI only for image generation.
"""
import argparse
import json
import random
import re
import subprocess
import sys
import time
import urllib.parse
import urllib.request
import uuid
from pathlib import Path

import yaml

DEFAULT_MODEL = "claude-haiku-4-5-20251001"
ROOT = Path(__file__).resolve().parent
DOCS_DIR = ROOT / "docs"

# width/height pairs (multiples of 64) per aspect setting
ASPECT_SIZES = {
    "21:9": (1536, 640),
    "16:9": (1344, 768),
    "3:2": (1216, 832),
    "1:1": (1024, 1024),
}


def load_config() -> dict:
    with open(ROOT / "config.yaml", encoding="utf-8") as f:
        return yaml.safe_load(f)["hero"]


def frontmatter(text: str) -> str:
    match = re.match(r"\A---\n(.*?)\n---", text, re.DOTALL)
    return match.group(1) if match else ""


def describe_with_claude(title: str, body: str, model: str) -> dict:
    """One Claude call returning both the hero image subject and a short
    page summary."""
    prompt = f"""You are preparing a hero illustration subject and a short summary
for a web page. Below is the page content.

Page title: "{title}"

Output EXACTLY these two sections, each starting with its delimiter on
its own line, no other text before or after:

===SUBJECT===
ONE concrete visual scene that represents what the page is about.
Rules: 30 to 60 words, a single scene; concrete physical objects and
setting, no abstractions; no words or lettering anywhere in the scene;
no art style, medium, colour palette, or camera terms — subject only;
wide horizontal composition suitable for a banner.

===SUMMARY===
A 2-3 sentence summary (40-60 words) of what the page covers, so a
reader can quickly decide whether to read on. Matter-of-fact, plain
language, no hype, no exclamation marks. Describe the page's content,
not its quality.

--- PAGE CONTENT ---
{body[:8000]}
--- END PAGE CONTENT ---"""

    result = subprocess.run(
        ["claude", "-p", "--model", model],
        input=prompt,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if result.returncode != 0:
        sys.exit(f"Error calling Claude: {result.stderr}")
    match = re.search(r"===SUBJECT===\s*(.*?)\s*===SUMMARY===\s*(.+)",
                      result.stdout, re.DOTALL)
    if not match:
        sys.exit(f"Claude output missing sections:\n{result.stdout}")
    return {
        "subject": " ".join(match.group(1).split()),
        "summary": " ".join(match.group(2).split()),
    }


def comfyui_generate(cfg: dict, prompt: str, out_path: Path) -> None:
    width, height = ASPECT_SIZES.get(cfg["aspect"], ASPECT_SIZES["21:9"])
    workflow = {
        "1": {"class_type": "UNETLoader",
              "inputs": {"unet_name": cfg["unet"], "weight_dtype": "default"}},
        "2": {"class_type": "CLIPLoader",
              "inputs": {"clip_name": cfg["clip"], "type": "flux2",
                         "device": "default"}},
        "3": {"class_type": "VAELoader", "inputs": {"vae_name": cfg["vae"]}},
        "4": {"class_type": "CLIPTextEncode",
              "inputs": {"text": prompt, "clip": ["2", 0]}},
        "5": {"class_type": "CLIPTextEncode",
              "inputs": {"text": cfg.get("negative", ""), "clip": ["2", 0]}},
        "6": {"class_type": "EmptyFlux2LatentImage",
              "inputs": {"width": width, "height": height, "batch_size": 1}},
        "7": {"class_type": "KSampler",
              "inputs": {"model": ["1", 0], "positive": ["4", 0],
                         "negative": ["5", 0], "latent_image": ["6", 0],
                         "seed": random.randint(0, 2**48),
                         "steps": cfg["steps"], "cfg": cfg["cfg"],
                         "sampler_name": "euler", "scheduler": "simple",
                         "denoise": 1.0}},
        "8": {"class_type": "VAEDecode",
              "inputs": {"samples": ["7", 0], "vae": ["3", 0]}},
        "9": {"class_type": "SaveImage",
              "inputs": {"images": ["8", 0], "filename_prefix": "hero"}},
    }

    base = cfg["comfyui"].rstrip("/")
    body = json.dumps({"prompt": workflow, "client_id": uuid.uuid4().hex})
    request = urllib.request.Request(
        f"{base}/prompt", data=body.encode(),
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request) as response:
            prompt_id = json.load(response)["prompt_id"]
    except urllib.error.URLError as e:
        sys.exit(f"Cannot reach ComfyUI at {base}: {e}")

    print("Waiting for ComfyUI...", file=sys.stderr)
    deadline = time.time() + 600
    while time.time() < deadline:
        with urllib.request.urlopen(f"{base}/history/{prompt_id}") as response:
            history = json.load(response).get(prompt_id)
        if history:
            status = history.get("status", {})
            if status.get("status_str") == "error":
                sys.exit(f"ComfyUI error: {json.dumps(status, indent=2)[:2000]}")
            if history.get("outputs"):
                break
        time.sleep(2)
    else:
        sys.exit("Timed out waiting for ComfyUI after 10 minutes.")

    image = history["outputs"]["9"]["images"][0]
    query = urllib.parse.urlencode({
        "filename": image["filename"],
        "subfolder": image.get("subfolder", ""),
        "type": image.get("type", "output"),
    })
    with urllib.request.urlopen(f"{base}/view?{query}") as response:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(response.read())


def set_frontmatter(md_path: Path, values: dict) -> None:
    """Set or replace top-level frontmatter keys."""
    text = md_path.read_text(encoding="utf-8")
    meta = frontmatter(text)
    if not meta:
        sys.exit(f"{md_path} has no frontmatter block to update.")
    for key, value in values.items():
        if re.search(rf"^{key}:", meta, re.MULTILINE):
            meta = re.sub(rf"^{key}:.*$", f"{key}: {value}", meta,
                          flags=re.MULTILINE)
        else:
            meta = f"{meta}\n{key}: {value}"
    body = text[re.match(r"\A---\n.*?\n---", text, re.DOTALL).end():]
    md_path.write_text(f"---\n{meta}\n---{body}", encoding="utf-8", newline="\n")


def yaml_quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def wants_summary(text: str) -> bool:
    """A page needs a generated summary unless it already has one in the
    frontmatter or a '## Summary' section in the body (video pages)."""
    if re.search(r"^summary:", frontmatter(text), re.MULTILINE):
        return False
    return not re.search(r"^## Summary\s*$", text, re.MULTILINE)


def page_title(text: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else ""


def hero_name(md_path: Path) -> str:
    stem = md_path.stem if md_path.stem != "index" else md_path.parent.name
    return f"{stem}-hero.png"


def bulk_targets(summary_only: bool) -> list[Path]:
    """Content pages needing work, skipping structural pages and daily
    posts."""
    targets = []
    for md in sorted(DOCS_DIR.rglob("*.md")):
        rel = md.relative_to(DOCS_DIR).as_posix()
        if rel in ("index.md", "tags.md") or rel.startswith(("author/", "posts/")):
            continue
        text = md.read_text(encoding="utf-8")
        if summary_only:
            if wants_summary(text):
                targets.append(md)
        elif not re.search(r"^image:", frontmatter(text), re.MULTILINE):
            targets.append(md)
    return targets


def process(md_path: Path, cfg: dict, style_key: str, model: str,
            force: bool, summary_only: bool) -> None:
    text = md_path.read_text(encoding="utf-8")
    has_image = bool(re.search(r"^image:", frontmatter(text), re.MULTILINE))
    need_image = not summary_only and (force or not has_image)
    need_summary = wants_summary(text) or (summary_only and force)
    if not need_image and not need_summary:
        print(f"Skipping (nothing to do): {md_path}")
        return

    title = page_title(text) or md_path.stem
    print(f"\n{md_path}", file=sys.stderr)
    print("Asking Claude...", file=sys.stderr)
    sections = describe_with_claude(title, text, model)

    updates = {}
    if need_summary:
        print(f"Summary: {sections['summary']}", file=sys.stderr)
        updates["summary"] = yaml_quote(sections["summary"])
    if need_image:
        if style_key == "random":
            style_key = random.choice(list(cfg["styles"]))
        print(f"Style: {style_key}", file=sys.stderr)
        print(f"Subject: {sections['subject']}", file=sys.stderr)
        out_path = md_path.parent / "img" / hero_name(md_path)
        comfyui_generate(cfg, f"{sections['subject']}, {cfg['styles'][style_key]}",
                         out_path)
        updates["image"] = f"img/{out_path.name}"
        updates["image_style"] = style_key
        print(f"Created: {out_path}")

    set_frontmatter(md_path, updates)
    print(f"Updated: {md_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate hero images for pages via ComfyUI."
    )
    parser.add_argument("paths", nargs="*", help="markdown file paths")
    parser.add_argument("--all", action="store_true",
                        help="all content pages that lack an image "
                             "(or a summary, with --summary)")
    parser.add_argument("--summary", action="store_true",
                        help="add page summaries only; no image, no ComfyUI needed")
    parser.add_argument("--force", action="store_true",
                        help="regenerate even if the page already has one")
    parser.add_argument("--style", help="override the style from config.yaml")
    parser.add_argument("-m", "--model", default=DEFAULT_MODEL,
                        help=f"Claude model (default: {DEFAULT_MODEL})")
    args = parser.parse_args()

    cfg = load_config()
    style_key = args.style or cfg.get("style", "random")
    if style_key != "random" and style_key not in cfg["styles"]:
        sys.exit(f"Unknown style '{style_key}'. "
                 f"Options: random, {', '.join(cfg['styles'])}")

    if args.all:
        targets = bulk_targets(args.summary)
        if not targets:
            thing = "summary" if args.summary else "image"
            print(f"Every content page already has a {thing}.")
            return
    elif args.paths:
        targets = [Path(p) for p in args.paths]
        for t in targets:
            if not t.exists():
                sys.exit(f"Not found: {t}")
    else:
        parser.error("give one or more markdown paths, or --all")

    for md_path in targets:
        process(md_path, cfg, style_key, args.model, args.force, args.summary)

    print("\nDone. Run: mkdocs build --strict")


if __name__ == "__main__":
    main()
